# Configuración para datos reales de MDS
## Include all genes, Cyto IPSSR, individual karyotypes and all clinical variables 
## (exclude MONOCYTES and PB_BLASTS due to missings)

# Rutas de datos de entrada (adaptadas al formato del pipeline)
data_paths:
  base_path: "./"
  
  # Archivo principal con variables clínicas y folds de CV
  clinical_mutations_file: "results/gnn/preprocess/clinical_fold.tsv"
  
  # Archivo con mutaciones (se adaptará el formato)
  mutations_vaf_file: "data/IPSSMol/maf.tsv"
  
  # Archivo con embeddings de genes
  gene_embeddings_file: "results/preprocess/gene_embedding_reduced.tsv"

  transformer_file: "results/gnn/preprocess/full_input/fitted_transformers/preprocessing_pipeline.pkl"

# Configuración del procesamiento de variables
variable_processing:
  # Variables continuas que necesitan escalado
  continuous_variables:
    - "BM_BLAST"
    - "WBC"
    - "ANC"
    - "HB"
    - "PLT"

  
  # Variables categóricas que necesitan encoding
  categorical_variables:
    - "SEX"
    - "CYTO_IPSSR"
    - "complex"
  
  # Variables binarias (sin procesamiento especial)
  binary_variables: ["plus8", "del7", "del20q", "del7q", "delY",
    "del5q"]
  
  # Variables de supervivencia (outputs del modelo)
  survival_variables:
    time_variable: "LFS_YEARS"
    status_variable: "LFS_STATUS"
  
  # Selección de genes (automática desde archivo de mutaciones)
  gene_selection: []

data_generation:
  output_formats:
    - "graph" 
  output_filename: "full_model_individual"
