# Configuración para datos reales de MDS
# Pipeline unificado para preparación de datos - Datos Reales

# Rutas de datos de entrada (adaptadas al formato del pipeline)
data_paths:
  base_path: "./"
  
  # Archivo principal con variables clínicas y folds de CV
  clinical_mutations_file: "results/gnn/preprocess/clinical_fold.tsv"
  
  # Archivo con mutaciones (se adaptará el formato)
  mutations_vaf_file: "data/IPSSMol/maf.tsv"
  
  # Archivo con embeddings de genes
  gene_embeddings_file: "results/preprocess/gene_embedding_reduced.tsv"

# Configuración del procesamiento de variables
variable_processing:
  # Variables continuas que necesitan escalado
  continuous_variables:
    - "AGE"
    - "BM_BLAST"
    - "PB_BLAST" 
    - "WBC"
    - "ANC"
    - "MONOCYTES"
    - "HB"
    - "PLT"
    - "RINGED_SIDEROBLASTS"
    - "IPSSR_SCORE"
    - "IPSSRA_SCORE"
    - "IPSSM_SCORE"
  
  # Variables categóricas que necesitan encoding
  categorical_variables:
    - "SEX"
  
  # Variables binarias (sin procesamiento especial)
  binary_variables: []
  
  # Variables de supervivencia (outputs del modelo)
  survival_variables:
    time_variable: "LFS_YEARS"
    status_variable: "LFS_STATUS"
  
  # Selección de genes (automática desde archivo de mutaciones)
  gene_selection: [
      "TP53",
      "ASXL1", 
      "SF3B1",
      "DNMT3A",
      "SRSF2",
      "RUNX1",
      "TET2",
      "IDH1",
      "IDH2",
      "U2AF1"
    ]  

# Configuración para generación de datos
data_generation:
  output_formats:
    - "table"  # Para modelos NN tradicionales
    - "graph"  # Para modelos GNN
  
  table_format:
    include_all_clinical: true
    output_filename: "real_data_table"
  
  graph_format:
    graph_type: "patient_gene"
    patient_node_features: "clinical_only"
    gene_node_features:
      embedding_source: "file"
      embedding_dimension: 16  # Según el archivo de embeddings
    edge_criteria:
      use_vaf_filter: false  # No hay VAF en df_mut
      min_vaf_threshold: 0.0
    output_filename: "real_data_graph"

# Cross-validation (usar folds existentes)
cross_validation:
  n_folds: 10
  fold_column: "fold"

# Configuración de salida
output:
  file_formats:
    tables: "pickle"
    graphs: "pickle" 
    metadata: "json"
  validate_output: true
  save_config_copy: true

# Configuración de logging
logging:
  level: "INFO"
  save_to_file: true
  log_filename: "real_data_pipeline.log"
