#' ---------------------------
#'
#' Purpose of script:
#'
#'  Explore gene embeddings from scGPT
#' 
#' ---------------------------
#'
#' Notes:
#' This script explores the gene embeddings generated by scGPT. It visualizes
#' the embeddings using PCA, and provides a summary of the embeddings.
#' 
#' Docker command:   
#' docker run -it -v $PWD:$PWD -w $PWD mds_subtypes_rsession:1.6 R
#'
#' ---------------------------

## Load libraries and data
library(tidyverse)
library(biomaRt)

## Get list of coding genes
ensembl <- useMart("ensembl", dataset = "hsapiens_gene_ensembl")
coding_genes <- getBM(
  attributes = c("ensembl_gene_id", "hgnc_symbol", "gene_biotype"),
  filters = "biotype",
  values = "protein_coding",
  mart = ensembl
)
save(coding_genes, file = "results/preprocess/coding_genes.Rdata")
write.table(coding_genes, file = "results/preprocess/coding_genes.txt", sep = "\t", 
  row.names = FALSE, col.names = TRUE, quote = FALSE)

## Get list of genes with mutations
mutation <- read_tsv("./data/IPSSMol/df_mut.tsv")
genes <- colnames(mutation)

embeddings <- read_delim("results/preprocess/gene_embedding_scgpt.tsv", delim = "\t")

## Visualize the embeddings using PCA
pca_result <- prcomp(embeddings[, -1])

pca_data <- as.data.frame(pca_result$x)
pca_data$Gene <- unlist(embeddings[, 1])
pca_data <- pca_data %>%
  left_join(coding_genes, by = c("Gene" = "hgnc_symbol")) %>%
  mutate(gene_biotype = ifelse(is.na(gene_biotype), "non-coding", gene_biotype)) %>%
  dplyr::select(-ensembl_gene_id)

# Plot PCA results
png("figures/geneEmbeddings/pca_coding_type.png", width = 1500, height = 1100, res = 300)
ggplot(pca_data, aes(x = PC1, y = PC2, color = gene_biotype)) +
  geom_point(alpha = 0.1) +
  labs(title = "PCA of scGPT Gene Embeddings",
       x = "PC1",
       y = "PC2") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))
dev.off()
summary(lm(PC1 ~ gene_biotype, pca_data))


png("figures/geneEmbeddings/pca_coding_type_density.png", width = 1500, height = 1100, res = 300)
ggplot(pca_data, aes(x = PC1, color = gene_biotype)) +
  geom_density() +
  labs(title = "Density Plot of PCA of scGPT Gene Embeddings",
       x = "PC1",
       y = "Density") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))
dev.off()

## Subset only coding genes
coding_embeddings <- embeddings[unlist(embeddings[, 1]) %in% coding_genes$hgnc_symbol, ]

pca_coding <- prcomp(coding_embeddings[, -1])
pca_coding_data <- as.data.frame(pca_coding$x)
pca_coding_data$Gene <-  unlist(coding_embeddings[, 1])
pca_coding_data$IPSSM <- ifelse(pca_coding_data$Gene %in% genes, "IPSSM", "Other")

# Plot PCA results for coding genes with IPSSM

png("figures/geneEmbeddings/pca_coding_gene_embeddings_ipssm.png", width = 1500, height = 1100, res = 300)
ggplot(pca_coding_data, aes(x = PC1, y = PC2, color = IPSSM)) +
  geom_point() +
  labs(title = "PCA of scGPT Coding Gene Embeddings in IPSSM",
       x = "PC1",
       y = "PC2") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))
dev.off()

## Compare average pairwise similarity of coding genes vs. IPSSM genes
average_pairwise_similarity <- function(embeddings) {
  # Calculate pairwise cosine similarity
  sim_matrix <- as.matrix(embeddings) %*% t(as.matrix(embeddings))
  diag(sim_matrix) <- 0  # Remove self-similarity
  mean(sim_matrix[upper.tri(sim_matrix)])  # Return average of upper triangle
}

genes <- genes[genes %in% unlist(coding_embeddings[, 1])]

embedding_t <- as.matrix(coding_embeddings[, -1])
rownames(embedding_t) <- unlist(coding_embeddings[, 1])
ipssm_embeddings <- as.matrix(embedding_t[genes, ])
ipssm_avg_similarity <- average_pairwise_similarity(ipssm_embeddings)

## Get average pairwise similarity for random sets of genes
set.seed(42)  # for reproducibility

n_iterations <- 1000
all_genes <- rownames(embedding_t)

random_avg_similarity <- sapply(seq_len(n_iterations), function(x) {
  random_genes <- sample(all_genes, length(genes), replace = FALSE)
  rand_emb <- as.matrix(embedding_t[random_genes, ])
  average_pairwise_similarity(rand_emb)
})

mean(ipssm_avg_similarity < random_avg_similarity)

## Evaluate reduced embeddings
reduced_embeddings <- read_delim("results/preprocess/gene_embedding_reduced.tsv", delim = "\t")

emb_mat <- as.matrix(embeddings[, -1])
rownames(emb_mat) <- unlist(embeddings[, 1])

red_emb_mat <- as.matrix(reduced_embeddings[, -1])
rownames(red_emb_mat) <- unlist(reduced_embeddings[, 1])

mini_red_emb <- head(red_emb_mat, 50)
d_red <- dist(mini_red_emb)

mini_emb <- emb_mat[rownames(mini_red_emb), ]
d_emb <- dist(mini_emb)

pca_coding_red <- prcomp(red_emb_mat)
pca_coding_red_data <- as.data.frame(pca_coding_red$x)
pca_coding_red_data$Gene <-  rownames(pca_coding_red_data)
pca_coding_red_data$IPSSM <- ifelse(pca_coding_red_data$Gene %in% genes, "IPSSM", "Other")

# Plot PCA

png("figures/geneEmbeddings/pca_coding_reduced_gene_embeddings_ipssm.png", width = 1500, height = 1100, res = 300)
ggplot(pca_coding_red_data, aes(x = PC1, y = PC2, color = IPSSM)) +
  geom_point() +
  labs(title = "PCA of scGPT Coding Gene Embeddings in IPSSM",
       x = "PC1",
       y = "PC2") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))
dev.off()
